inherit_from: .rubocop_todo.yml

require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - bin/*
    - db/*schema*.rb
    - config/**/*
    - tmp/**/*
    - storage/**/*
    - doc/**/*
    - coverage/**/*
    - node_modules/**/*
    - 'vendor/**/*'
    - test/**/*